### ISSUE TITLE
Unexpected result in read_u8xx methods

### ISSUE THREAD

**Issue by whiteh0le** [adrianherrera/kaitai_struct_lua_runtime#13] opened 2020-11-28 03:51 UTC
# Explanation
If you try to read an unsigned eight byte number with the most significant bit set you will get a negative number instead of a positive number. The reason is that the function string.unpack will return a `lua_integer` (signed integer in C)  even if we want an unsigned integer.

As a consequence, we can't read positive numbers between 2^64 and 2^65 - 1 correctly. This bug has been reported on the [lua mailing list](http://lua-users.org/lists/lua-l/2020-03/msg00061.html).
# Steps to reproduce
On the lua interpreter type:
```lua
string.unpack("I8", "\255\255\255\255\255\255\255\255")
-1     9 -- Expected 18446744073709551615
```
# Possible solution
Is not pretty, but a workaround is to use:
```lua
tonumber(string.format("%u", string.unpack('I8', self._io:read(8))))
18446744073709551615
```
I didn't make a pull request with the fix because I'm not sure there's a better way to do it.

Edit: I created this issue because the bug described in #2 is not resolved.

**Comment by dgelessus** [comment] 2020-11-28 17:33
As I understand it, this isn't exactly a bug, just an unfortunate side effect of how `string.unpack` interacts with Lua's number system. Lua supports storing numbers as either a signed integer or a float. When `string.unpack` reads an integer value, it always returns the result as an integer, so that no precision is lost. This happens even when reading an *unsigned* integer that is as large as Lua's native integer size - in that case, as you're seeing, it's silently converted to a signed integer, because Lua doesn't support unsigned integers natively. This behavior is used as a compromise - it allows working with unsigned integers that are as large as the native signed integer size, without losing precision, but with the disadvantage that the integers are incorrectly interpreted as signed by most operations, unless you explicitly say otheriwse like with `%u`.

The workaround that you've posted converts the integer to a string (explicitly using `%u` so that it's displayed as unsigned even though it's internally stored as signed), and then converts it back to a number. However, `tonumber` doesn't always return an integer - it will silently return a float instead if the number doesn't fit into Lua's native integer size. This will cause loss of precision for large numbers like these, because it's impossible to store the exact value of every 64-bit integer (signed or unsigned) in a 64-bit float. For example:

```lua
> ("%u"):format(-1)
18446744073709551615
> ("%f"):format(tonumber(("%u"):format(-1)))
18446744073709551616.000000
```

This behavior isn't suitable for every use case - sometimes you need the exact value of an unsigned integer but don't care about signed vs. unsigned (e. g. bitwise operations) or know how to work around this behavior using `%u`, etc. If your use case needs the correct sign but doesn't care about the slight loss of precision, you can use the `%u`/`tonumber` workaround in your own code. We can't unconditionally do this workaround in the Kaitai Struct-generated code, because that would lead to irreversible loss of precision, even for users who need the exact values.

Lua isn't the only language that does something like this by the way. For example, Java only has native integer types up to `long` (64-bit) and doesn't natively support unsigned integers. To allow manipulating unsigned 64-bit integers without losing precision or having to use `BigInteger`, it provides utility methods like `Long.parseUnsignedLong` and `Long.toUnsignedString` that use the signed `long` type to store unsigned 64-bit integers. Kaitai Struct behaves similarly here - it [reads unsigned 64-bit integers as signed `long`](https://github.com/kaitai-io/kaitai_struct_java_runtime/blob/ea3abf89ee7745ac56c814202c4ddb26fc668e11/src/main/java/io/kaitai/struct/KaitaiStream.java#L135-L142) and assumes that the user knows how to handle this correctly.

**Comment by whiteh0le** [comment] 2020-11-28 21:29
Thank you for your detailed explanation!
> this isn't exactly a bug, just an unfortunate side effect of how `string.unpack` interacts with Lua's number system

I know is not a bug from the lua side as it works as intended, but I think it's a bug in kaitai because the user and the [tests](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/spec/lua/test_integers.lua#L15) expects an unsigned integer.

> We can't unconditionally do this workaround in the Kaitai Struct-generated code, because that would lead to irreversible loss of precision

Now this is something I don't understand, reading a number using readu8 should never result in a loss of precision? I mean, you are reading an unsigned integer and no matter its value + using the `%u / tonumber` workaround will result in the expected value. I understand that the lost of precision occurs when converting an integer outside the integer range to a float but that is not what we are doing here. We are just reading a value.

**Comment by dgelessus** [comment] 2020-11-29 14:30
> the user [...] expects an unsigned integer

Well, in that case the user expected wrong 😉 More seriously - we should document this somewhere, because for people who don't already know how Lua's integers work exactly, this is probably unexpected behavior and will look incorrect. Unfortunately we don't have *any* language-specific notes for Lua yet, and [the notes for Java](https://doc.kaitai.io/lang_java.html#_primitive_type_mapping) (where the situation is very similar) also don't explain very well how to handle unsigned 64-bit integers.

> the [tests](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/spec/lua/test_integers.lua#L15) expects an unsigned integer

That's definitely a bug in the compiler and/or test generator. The fix is probably the same as what's already done for Java - [writing large integers as hex literals instead of decimal](https://github.com/kaitai-io/kaitai_struct_compiler/blob/af69228e70cfdab96eb2fc334b9b0e8aab3c52aa/shared/src/main/scala/io/kaitai/struct/translators/JavaTranslator.scala#L13-L17). According to [the Lua docs](https://www.lua.org/manual/5.4/manual.html#3.1):

> Hexadecimal numerals with neither a radix point nor an exponent always denote an integer value; if the value overflows, it wraps around to fit into a valid integer.

This means that in Lua (assuming Lua was built with 64-bit integers), `0xffffffffffffffff == -1`, so the Lua test should check `luaunit.assertEquals(r.uint64, 0xffffffffffffffff)` instead.

> Now this is something I don't understand, reading a number using readu8 should never result in a loss of precision?

Right, the `string.unpack("<I8", ...)` on its own *doesn't* lose any precision, exactly because the unsigned value is wrapped around to signed. If you convert that integer to decimal using `string.format("%u", ...)`, you don't lose precision either. But if you then take that decimal string and parse it again using `tonumber`, Lua will notice that the value is too large for a signed integer and silently return a float instead, and this is where some precision is lost. This last part is why we can't safely use the `%u`/`tonumber` workaround in the Kaitai Struct runtime.

**Comment by whiteh0le** [comment] 2020-11-29 15:30
Okay, everything is clear now.
If it's okay with you, I'll write down what needs to be done so that me/other people know what to do.

1. Write the Lua-specific notes to document the quirks and ticks of the Lua runtime library with an emphasis in handling unsigned 64-bit integers.
2. Make ksc and/or kst write large integers in hexadecimal notation in Lua.

**Comment by dgelessus** [comment] 2020-11-30 14:09
I've opened separate issues for these two points now (kaitai-io/kaitai_struct#836 and kaitai-io/kaitai_struct#837), so I'll close this one. Thank you for the report!

**Closed as completed by dgelessus** 2020-11-30 14:09 UTC
Labels: question
