### ISSUE TITLE
[suggestion] lib file name conflict, maybe re-organize the structure?

### ISSUE THREAD

**Issue by robertlzj** [adrianherrera/kaitai_struct_lua_runtime#18] opened 2022-05-21 15:37 UTC
Hi, I'm not been guided for how to import this runtime library.
I found namespace conflict, especially `class`, `enum` etc, if I copy them to my 'lualibs' directly.

For `class`, `enum`, `string_stream`, `string_decode` and `kaitaistruct` all in the same folder level.
And only `kaitaistruct ` is exposed as interface I think.

So, I thought to organize based on `kaitaistruct` is nice.

- kaitaistruct.lua
- "kaitaistruct" directory
  - class.lua
  - enum.lua
  - string_stream.lua
  - string_decode.lua

And `require'kaitaistruct.class'`,  `require'kaitaistruct.enum'`,  `require'kaitaistruct.string_stream'`,  `require'kaitaistruct.string_decode'` internal.

**Comment by generalmimon** [comment] 2022-05-21 15:55
Duplicate of https://github.com/kaitai-io/kaitai_struct_lua_runtime/issues/11

Please continue the discussion there so we don't have multiple open issues for the same thing.

**Closed as completed by generalmimon** 2022-05-21 15:55 UTC
Labels: duplicate
